# Macro file for my He3


/run/initialize
/run/verbose 1
/random/setSeeds 238009 238117
/tracking/verbose 0

# list the existing physics processes
/process/list

/gps/particle neutron
/gps/pos/centre 0 0 -38.1 mm
/gps/pos/type Point
/gps/ang/type iso

/gps/ene/type Arb
/gps/hist/type arb

#/gps/hist/point <X> <Y> command is used to load the histogram,
# where <X> is the energy in MeV and Y is the weight (or area) of the bin.

/gps/hist/point 0. 0.
/gps/hist/point 0.1 2.72567
/gps/hist/point 0.2 6.29
/gps/hist/point 0.3 6.254
/gps/hist/point 0.4 6.17
/gps/hist/point 0.5 6.06833
/gps/hist/point 0.6 5.56
/gps/hist/point 0.7 5.53133
/gps/hist/point 0.8 4.72867
/gps/hist/point 0.9 4.7
/gps/hist/point 1. 4.3
/gps/hist/point 1.1 4.22
/gps/hist/point 1.2 3.877
/gps/hist/point 1.3 3.73
/gps/hist/point 1.4 3.577
/gps/hist/point 1.5 3.46
/gps/hist/point 1.6 3.603
/gps/hist/point 1.7 3.79
/gps/hist/point 1.8 3.91
/gps/hist/point 1.9 4.19
/gps/hist/point 2. 4.19833
/gps/hist/point 2.1 4.24
/gps/hist/point 2.2 4.24
/gps/hist/point 2.3 4.24
/gps/hist/point 2.4 4.24
/gps/hist/point 2.5 4.44833
/gps/hist/point 2.6 4.49
/gps/hist/point 2.7 5.239
/gps/hist/point 2.8 5.56
/gps/hist/point 2.9 6.393
/gps/hist/point 3. 7.03
/gps/hist/point 3.1 7.13833
/gps/hist/point 3.2 7.28
/gps/hist/point 3.3 7.052
/gps/hist/point 3.4 6.52
/gps/hist/point 3.5 6.44167
/gps/hist/point 3.6 6.05
/gps/hist/point 3.7 6.03667
/gps/hist/point 3.8 5.66333
/gps/hist/point 3.9 5.65
/gps/hist/point 4. 5.35833
/gps/hist/point 4.1 5.3
/gps/hist/point 4.2 5.545
/gps/hist/point 4.3 5.65
/gps/hist/point 4.4 5.84267
/gps/hist/point 4.5 5.99
/gps/hist/point 4.6 6.016
/gps/hist/point 4.7 6.05
/gps/hist/point 4.8 6.119
/gps/hist/point 4.9 6.28
/gps/hist/point 5. 6.23167
/gps/hist/point 5.1 5.99
/gps/hist/point 5.2 5.96267
/gps/hist/point 5.3 5.19733
/gps/hist/point 5.4 5.17
/gps/hist/point 5.5 4.695
/gps/hist/point 5.6 4.6
/gps/hist/point 5.7 4.229
/gps/hist/point 5.8 4.07
/gps/hist/point 5.9 3.70733
/gps/hist/point 6. 3.43
/gps/hist/point 6.1 3.46467
/gps/hist/point 6.2 3.51
/gps/hist/point 6.3 3.612
/gps/hist/point 6.4 3.85
/gps/hist/point 6.5 3.81
/gps/hist/point 6.6 3.61
/gps/hist/point 6.7 3.597
/gps/hist/point 6.8 3.233
/gps/hist/point 6.9 3.22
/gps/hist/point 7. 3.18667
/gps/hist/point 7.1 3.18
/gps/hist/point 7.2 3.271
/gps/hist/point 7.3 3.31
/gps/hist/point 7.4 3.446
/gps/hist/point 7.5 3.55
/gps/hist/point 7.6 3.58467
/gps/hist/point 7.7 3.63
/gps/hist/point 7.8 3.543
/gps/hist/point 7.9 3.34
/gps/hist/point 8. 3.235
/gps/hist/point 8.1 2.71
/gps/hist/point 8.2 2.68367
/gps/hist/point 8.3 1.94633
/gps/hist/point 8.4 1.92
/gps/hist/point 8.5 1.345
/gps/hist/point 8.6 1.23
/gps/hist/point 8.7 0.964
/gps/hist/point 8.8 0.85
/gps/hist/point 8.9 0.759333
/gps/hist/point 9. 0.69
/gps/hist/point 9.1 0.720333
/gps/hist/point 9.2 0.76
/gps/hist/point 9.3 0.832
/gps/hist/point 9.4 1.
/gps/hist/point 9.5 1.03
/gps/hist/point 9.6 1.18
/gps/hist/point 9.7 1.17767
/gps/hist/point 9.8 1.11233
/gps/hist/point 9.9 1.11
/gps/hist/point 10. 0.86
/gps/hist/point 10.1 0.81
/gps/hist/point 10.2 0.789
/gps/hist/point 10.3 0.78
/gps/hist/point 10.4 0.666667
/gps/hist/point 10.5 0.58
/gps/hist/point 10.6 0.463
/gps/hist/point 10.7 0.31
/gps/hist/point 10.8 0.244
/gps/hist/point 10.9 0.09
/gps/hist/point 11. 0.075
/gps/hist/point 11.1 0.
/gps/hist/point 11.2 0.
/gps/hist/point 11.3 0.
/gps/hist/point 11.4 0.
/gps/hist/point 11.5 0.
/gps/hist/point 11.6 0.
/gps/hist/point 11.7 0.
/gps/hist/point 11.8 0.
/gps/hist/point 11.9 0.
/gps/hist/point 12. 0.


/gps/hist/inter Lin

/run/printProgress 10000
/analysis/setFileName He3_2p5inch_AmBeISO_Sair_1m_SHB
/run/beamOn 1000000
