# Macro file for my He3
# 2" moderator thickness


/run/initialize
/tracking/verbose 0

# list the existing physics processes
/process/list

# isotropic neutrons 10MeV
/gps/particle neutron
/gps/pos/centre 0 0 -37.25 mm
#/gps/ang/mintheta 0 deg

/gps/pos/type Point
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 0.152 MeV
/run/printProgress 10000
/analysis/setFileName He3_2p5inch_YBe
/run/beamOn 1000000
